### ISSUE TITLE
big fileset doesn't work

### ISSUE THREAD

**Issue by javamakesmyday** [lene/DuplicateImages#8]
When working on large number of files in my case around 111,524 files with long files names and buried sub directories, files_in_dirs function fails. 

I wrote very preliminary function to get the file list and found using temp files to store the file names works well (though highly inefficient) but will always get the list of files without heavy memory overhead. 

I would recommend to convert the existing in memory list to the file structure.

I am not a python expert but will try to work on code and post it here.

**Comment by lene** [comment]
Thank you for reporting! I could not yet reproduce it yet (~180k files work fine on my machine, but I haven't yet tried to replicate the long filenames and deep directory structure you mentioned). Are you using it in a situation where memory on your machine is tight?

If you can work out a solution, that is of course welcome. Otherwise, the exact error message and stack traceback you encounter would also be helpful!

**Comment by javamakesmyday** [comment]
find-dups .  --parallel --progress --hash-db hashes.json
12:13:16 INFO: Scanning .
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/find-dups", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/duplicate_images/duplicate.py", line 79, in main
    matches = get_matches(
              ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/duplicate_images/duplicate.py", line 52, in get_matches
    image_files = sorted(files_in_dirs(root_directories, is_image_file))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/duplicate_images/duplicate.py", line 35, in files_in_dirs
    files = [
            ^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/duplicate_images/duplicate.py", line 40, in <listcomp>
    if is_file(Path(root) / filename)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/duplicate_images/duplicate.py", line 26, in is_image_file
    kind = guess(filename)
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/filetype/filetype.py", line 28, in guess
    return match(obj) if obj else None
           ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/filetype/match.py", line 30, in match
    buf = get_bytes(obj)
          ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/filetype/utils.py", line 73, in get_bytes
    return get_signature_bytes(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/filetype/utils.py", line 25, in get_signature_bytes
    return bytearray(fp.read(_NUM_SIGNATURE_BYTES))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 89] Operation canceled

**Comment by javamakesmyday** [comment]
Thinking more about it, there is also another possibility. I am running this code against onedrive. which means that all the files from onedirve needs to be downloaded and my Macbook might be out of space to download all the images. 

Trying it on Windows now.

**Comment by lene** [comment]
Thanks for your feedback! That you run it on OneDrive is particularly relevant here, because errno 89 signifies a socket error ("Destination address required"). I won't pretend to fully understand what is going on here, but my guess is that OneDrive tries to download the file and for some reason fails.

There is not much I can do against failures in the file system abstraction :) What I can (and will) do though is to guard against read failure in `is_image_file()`.  That way, files for which this error occurs will be skipped, but the program continues.

Thanks again for reporting this failure and reminding me of all the myriad ways in which things can go wrong!

**Comment by lene** [comment]
As an aside, I profiled the application and could not get the memory usage of `files_in_dirs()` to exceed 80MB, so I am very sure that memory usage is not the issue here.

**Comment by lene** [comment]
I implemented that guard against failure in `is_image_file`, you can try it in version 0.10.6, available now at https://pypi.org/project/duplicate_images/. I'd be delighted if you tell me how it goes!
